config/routes.rb
Reddit::Application.routes.draw do
  resources :votes

  resources :comments

  get "userprofile/index"

  get "home/index"

  get "home/about"

  get "home/contact"

  resources :posts

  devise_for :users

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :user_id, :post_id

  belongs_to :user
  belongs_to :post

  validates :text, :user_id, :post_id, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for @comment, :html => {:class=>"post-comment-form"} do |f|
  -#COMMENT: This is NOT safe - users can change the value in the browser
  -#and then comment as someone else.
  -# You could build a safeguard into posts_controller#create or utilize
  -# CanCan (recommended)
  = f.hidden_field :user_id, :value => current_user.id
  = f.hidden_field :post_id, :value => post.id
  = f.text_field :text, :class => 'text_field'
  = f.submit nil, :class => 'btn btn-primary'

app/views/comments/_show_comments.html.haml
-comments.each do |c|
  %p
    ="#{c.created_at.strftime("%m/%d/%Y %H.%M %p")} #{c.user.username}"
    %br
    %blockquote=c.text

app/views/comments/edit.html.haml
-#COMMENT: It is confusing if you leave the scaffolded views around. Just sayin'
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/index.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to comment.id, comment_path(comment)
        %td= comment.user_id
        %td= comment.text
        %td=l comment.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(comment), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(comment), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_comment_path, :class => 'btn btn-primary'

app/views/comments/new.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/comments/show.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @comment.user_id
%p
  %strong= model_class.human_attribute_name(:text) + ':'
  %br
  = @comment.text

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), comments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(@comment), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(@comment), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'