config/routes.rb
Reddit::Application.routes.draw do
  resources :votes

  resources :comments

  get "userprofile/index"

  get "home/index"

  get "home/about"

  get "home/contact"

  resources :posts

  devise_for :users

  root :to => 'home#index'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post_id, :up_or_down, :user_id

  belongs_to :user
  belongs_to :post

  #COMMENT: The up_or_down field should be called up, 
  #since the boolean indicates whether the vote is an upvote.
  validates :up_or_down, :user_id, :post_id, :presence => true
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @votes }
    end
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @vote = Vote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end

  # GET /votes/1/edit
  def edit
    @vote = Vote.find(params[:id])
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(params[:vote])

    respond_to do |format|
      if @vote.save
        format.html { redirect_to :back, notice: 'Vote was successfully created.' }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { render action: "new" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    @vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.haml
= form_for @vote, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :post_id, :class => 'control-label'
    .controls
      = f.number_field :post_id, :class => 'number_field'
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .control-group
    = f.label :up_or_down, :class => 'control-label'
    .controls
      = f.check_box :up_or_down, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), votes_path, :class => 'btn'

app/views/votes/_voting.html.haml
-if user_signed_in? && current_user.can_vote?(post.id)
  .post-voting-tools
    -#COMMENT: This is workin well and is almost the correct approach.
    -#But: we don't want to mix our Javascript and HTML if it can be separated
    -#cleaner while enforcing semantic markup. Have a look at http://de.wikipedia.org/wiki/Unobtrusive_JavaScript and especially http://railscasts.com/episodes/205-unobtrusive-javascript?language=de&view=asciicast
    - form_id = "vote_for_#{post.id}"
    - text_id = "value_for_#{post.id}"
    - signature ="javascript: submit_vote('#{form_id}','#{text_id}',"
    /- signature ="say("

    %div{:class =>"icon-chevron-up btn left", :onclick=>"#{signature}'1')"}
    %div{:class=>"icon-chevron-down btn left", :onclick=>"#{signature}'0')"}

    :javascript
      function submit_vote(form_id, text_id, value){
        $('#'+text_id).val(value);
        $('#'+form_id).submit();
      }

    - #COMMENT: Either instantiate this in the controller or simply use a symbol (":vote") instead of ("@vote") or post.votes.build
    -@vote=Vote.new
    = form_for @vote, :html => { :class => 'form-horizontal', :id => form_id} do |f|
      = f.hidden_field :post_id, :value => post.id
      = f.hidden_field :user_id, :value => current_user.id
      = f.hidden_field :up_or_down, :id=> text_id,:value => '0'

app/views/votes/edit.html.haml
- model_class = Vote
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/votes/index.html.haml
- model_class = Vote
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:post_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:up_or_down)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @votes.each do |vote|
      %tr
        %td= link_to vote.id, vote_path(vote)
        %td= vote.post_id
        %td= vote.user_id
        %td= vote.up_or_down
        %td=l vote.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_vote_path(vote), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), vote_path(vote), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_vote_path, :class => 'btn btn-primary'

app/views/votes/new.html.haml
- model_class = Vote
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/votes/show.html.haml
- model_class = Vote
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:post_id) + ':'
  %br
  = @vote.post_id
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @vote.user_id
%p
  %strong= model_class.human_attribute_name(:up_or_down) + ':'
  %br
  = @vote.up_or_down

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), votes_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_vote_path(@vote), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), vote_path(@vote), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'